"""add clean and aggressive anchor columns

Revision ID: 833a9c49195a
Revises: 56327c736d47
Create Date: 2026-09-09 09:36:39.184744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '833a9c49195a'
down_revision: Union[str, Sequence[str], None] = '56327c736d47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playbook_rules', sa.Column('clean_anchor', sa.Float(), nullable=True))
    op.add_column('playbook_rules', sa.Column('aggressive_anchor', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playbook_rules', 'aggressive_anchor')
    op.drop_column('playbook_rules', 'clean_anchor')
    # ### end Alembic commands ###
