"""make obligation due_date nullable, add period_description

Revision ID: a0bfbf34ed6a
Revises: 833a9c49195a
Create Date: 2026-09-10 08:35:13.668614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0bfbf34ed6a'
down_revision: Union[str, Sequence[str], None] = '833a9c49195a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('obligations', sa.Column('period_description', sa.String(), nullable=True))
    op.alter_column('obligations', 'due_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_column('obligations', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('obligations', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('obligations', 'due_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('obligations', 'period_description')
    # ### end Alembic commands ###
