"""add raw_text to contracts

Revision ID: b9468b02c03d
Revises: 99806206d91d
Create Date: 2026-09-08 10:03:24.248835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9468b02c03d'
down_revision: Union[str, Sequence[str], None] = '99806206d91d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('raw_text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'raw_text')
    # ### end Alembic commands ###
