"""add summary column to contracts

Revision ID: d828ab5af731
Revises: a0bfbf34ed6a
Create Date: 2026-09-16 05:35:36.425067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd828ab5af731'
down_revision: Union[str, Sequence[str], None] = 'a0bfbf34ed6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('summary', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'summary')
    # ### end Alembic commands ###
